name: master_ci_cd

on:
  push:
    branches: "main"


jobs:
  teams_message:
    name: "Send a message on teams"
    runs-on: ubuntu-latest
    steps:
      - name: Send message to ms teams
        uses: dhollerbach/github-action-send-message-to-ms-teams@1.0.10
        with:
          webhook: ${{ SECRETS.TEAMS_URL }}
          message: '
            {
             "type":"message",
             "attachments":[
                {
                   "contentType":"application/vnd.microsoft.card.adaptive",
                   "contentUrl":null,
                   "content":{
                      "$schema":"http://adaptivecards.io/schemas/adaptive-card.json",
                      "type":"AdaptiveCard",
                      "version":"1.2",
                      "body":[
                          {
                          "type": "TextBlock",
                          "text": "For Samples and Templates, see [https://adaptivecards.io/samples](https://adaptivecards.io/samples)"
                          }
                      ]
                   }
                }
             ]
          }'